export const APP_CONSTANTS = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
  SALT_ROUNDS: 12,
  REQUEST_ID_HEADER: 'x-request-id',
  MAX_SESSIONS_PER_USER: 5,
  SESSION_CACHE_TTL: 3600,
  PASSWORD_RESET_EXPIRES_MINUTES: 15,
  EMAIL_VERIFICATION_EXPIRES_MINUTES: 60,
  EMAIL_VERIFICATION_COOLDOWN_MINUTES: 1,
} as const;
